language: c
compiler: gcc
matrix:
  fast_finish: true
  include:
    # Container-based Ubuntu 12.04 LTS Server Edition 64 bit (doesn't support 32-bit includes)
    - os: linux
      sudo: false
      env: PLATFORM="Ubuntu 12.04 container" CMD="make travis-install"
    - os: linux
      sudo: false
      env: PLATFORM="Ubuntu 12.04 container" CMD="make cmaketest"
    - os: linux
      sudo: false
      env: PLATFORM="Ubuntu 12.04 container" CMD="make test"
    - os: linux
      sudo: false
      env: PLATFORM="Ubuntu 12.04 container" CMD="make -C programs test-zstd_nolegacy"
    - os: linux
      sudo: false
      env: PLATFORM="Ubuntu 12.04 container" CMD="make usan"
    - os: linux
      sudo: false
      env: PLATFORM="Ubuntu 12.04 container" CMD="make asan"
    - os: linux
      sudo: false
      env: PLATFORM="Ubuntu 12.04 container" CMD="make zlibwrapper"
    # Standard Ubuntu 12.04 LTS Server Edition 64 bit
    - os: linux
      sudo: required
      env: PLATFORM="Ubuntu 12.04" CMD="make libc6install clangtest"
    - os: linux
      sudo: required
      env: PLATFORM="Ubuntu 12.04" CMD="make gppinstall gpptest"
    - os: linux
      sudo: required
      env: PLATFORM="Ubuntu 12.04" CMD="make libc6install gnu90test"
    - os: linux
      sudo: required
      env: PLATFORM="Ubuntu 12.04" CMD="make libc6install c99test"
    - os: linux
      sudo: required
      env: PLATFORM="Ubuntu 12.04" CMD="make libc6install gnu99test"
    - os: linux
      sudo: required
      env: PLATFORM="Ubuntu 12.04" CMD="make arminstall armtest"
    - os: linux
      sudo: required
      env: PLATFORM="Ubuntu 12.04" CMD="make libc6install && make -C programs test32"
    - os: linux
      sudo: required
      env: PLATFORM="Ubuntu 12.04" CMD="make -C tests versionsTest"
    - os: linux
      sudo: required
      env: PLATFORM="Ubuntu 12.04" CMD="make libc6install asan32"
    - os: linux
      sudo: required
      env: PLATFORM="Ubuntu 12.04" CMD="make valgrindinstall && make -C programs valgrindTest"
    # Ubuntu 14.04 LTS Server Edition 64 bit
    - os: linux
      dist: trusty
      sudo: required
      env: PLATFORM="Ubuntu 14.04" CMD="make gcc5install gcc5test"
    - os: linux
      dist: trusty
      sudo: required
      env: PLATFORM="Ubuntu 14.04" CMD="make gcc6install gcc6test"
    - os: linux
      dist: trusty
      sudo: required
      env: PLATFORM="Ubuntu 14.04" CMD="make ppcinstall ppctest"
    - os: linux
      dist: trusty
      sudo: required
      env: PLATFORM="Ubuntu 14.04" CMD="make zlibwrapper"
    # OS X Mavericks
    - os: osx
      env: PLATFORM="OS X Mavericks" CMD="make travis-install"
    - os: osx
      env: PLATFORM="OS X Mavericks" CMD="make gnu90test"
    - os: osx
      env: PLATFORM="OS X Mavericks" CMD="make test"
  exclude:
    - compiler: gcc

script:
  - sh -c "$CMD"
